/** Dial codes for every common calling destination — searchable by name or code. */
export interface PhoneCode {
  iso: string
  name: string
  code: string
  flag: string
}

export const PHONE_CODES: PhoneCode[] = [
  { iso: 'AF', name: 'Afghanistan', code: '+93', flag: '🇦🇫' },
  { iso: 'AL', name: 'Albania', code: '+355', flag: '🇦🇱' },
  { iso: 'DZ', name: 'Algeria', code: '+213', flag: '🇩🇿' },
  { iso: 'AD', name: 'Andorra', code: '+376', flag: '🇦🇩' },
  { iso: 'AO', name: 'Angola', code: '+244', flag: '🇦🇴' },
  { iso: 'AR', name: 'Argentina', code: '+54', flag: '🇦🇷' },
  { iso: 'AM', name: 'Armenia', code: '+374', flag: '🇦🇲' },
  { iso: 'AU', name: 'Australia', code: '+61', flag: '🇦🇺' },
  { iso: 'AT', name: 'Austria', code: '+43', flag: '🇦🇹' },
  { iso: 'AZ', name: 'Azerbaijan', code: '+994', flag: '🇦🇿' },
  { iso: 'BS', name: 'Bahamas', code: '+1242', flag: '🇧🇸' },
  { iso: 'BH', name: 'Bahrain', code: '+973', flag: '🇧🇭' },
  { iso: 'BD', name: 'Bangladesh', code: '+880', flag: '🇧🇩' },
  { iso: 'BB', name: 'Barbados', code: '+1246', flag: '🇧🇧' },
  { iso: 'BY', name: 'Belarus', code: '+375', flag: '🇧🇾' },
  { iso: 'BE', name: 'Belgium', code: '+32', flag: '🇧🇪' },
  { iso: 'BZ', name: 'Belize', code: '+501', flag: '🇧🇿' },
  { iso: 'BJ', name: 'Benin', code: '+229', flag: '🇧🇯' },
  { iso: 'BT', name: 'Bhutan', code: '+975', flag: '🇧🇹' },
  { iso: 'BO', name: 'Bolivia', code: '+591', flag: '🇧🇴' },
  { iso: 'BA', name: 'Bosnia and Herzegovina', code: '+387', flag: '🇧🇦' },
  { iso: 'BW', name: 'Botswana', code: '+267', flag: '🇧🇼' },
  { iso: 'BR', name: 'Brazil', code: '+55', flag: '🇧🇷' },
  { iso: 'BN', name: 'Brunei', code: '+673', flag: '🇧🇳' },
  { iso: 'BG', name: 'Bulgaria', code: '+359', flag: '🇧🇬' },
  { iso: 'BF', name: 'Burkina Faso', code: '+226', flag: '🇧🇫' },
  { iso: 'BI', name: 'Burundi', code: '+257', flag: '🇧🇮' },
  { iso: 'KH', name: 'Cambodia', code: '+855', flag: '🇰🇭' },
  { iso: 'CM', name: 'Cameroon', code: '+237', flag: '🇨🇲' },
  { iso: 'US', name: 'United States', code: '+1', flag: '🇺🇸' },
  { iso: 'CA', name: 'Canada', code: '+1', flag: '🇨🇦' },
  { iso: 'CV', name: 'Cape Verde', code: '+238', flag: '🇨🇻' },
  { iso: 'CF', name: 'Central African Republic', code: '+236', flag: '🇨🇫' },
  { iso: 'TD', name: 'Chad', code: '+235', flag: '🇹🇩' },
  { iso: 'CL', name: 'Chile', code: '+56', flag: '🇨🇱' },
  { iso: 'CN', name: 'China', code: '+86', flag: '🇨🇳' },
  { iso: 'CO', name: 'Colombia', code: '+57', flag: '🇨🇴' },
  { iso: 'KM', name: 'Comoros', code: '+269', flag: '🇰🇲' },
  { iso: 'CG', name: 'Congo', code: '+242', flag: '🇨🇬' },
  { iso: 'CD', name: 'Congo (DRC)', code: '+243', flag: '🇨🇩' },
  { iso: 'CR', name: 'Costa Rica', code: '+506', flag: '🇨🇷' },
  { iso: 'HR', name: 'Croatia', code: '+385', flag: '🇭🇷' },
  { iso: 'CU', name: 'Cuba', code: '+53', flag: '🇨🇺' },
  { iso: 'CY', name: 'Cyprus', code: '+357', flag: '🇨🇾' },
  { iso: 'CZ', name: 'Czechia', code: '+420', flag: '🇨🇿' },
  { iso: 'DK', name: 'Denmark', code: '+45', flag: '🇩🇰' },
  { iso: 'DJ', name: 'Djibouti', code: '+253', flag: '🇩🇯' },
  { iso: 'DM', name: 'Dominica', code: '+1767', flag: '🇩🇲' },
  { iso: 'DO', name: 'Dominican Republic', code: '+1809', flag: '🇩🇴' },
  { iso: 'EC', name: 'Ecuador', code: '+593', flag: '🇪🇨' },
  { iso: 'EG', name: 'Egypt', code: '+20', flag: '🇪🇬' },
  { iso: 'SV', name: 'El Salvador', code: '+503', flag: '🇸🇻' },
  { iso: 'GQ', name: 'Equatorial Guinea', code: '+240', flag: '🇬🇶' },
  { iso: 'ER', name: 'Eritrea', code: '+291', flag: '🇪🇷' },
  { iso: 'EE', name: 'Estonia', code: '+372', flag: '🇪🇪' },
  { iso: 'SZ', name: 'Eswatini', code: '+268', flag: '🇸🇿' },
  { iso: 'ET', name: 'Ethiopia', code: '+251', flag: '🇪🇹' },
  { iso: 'FJ', name: 'Fiji', code: '+679', flag: '🇫🇯' },
  { iso: 'FI', name: 'Finland', code: '+358', flag: '🇫🇮' },
  { iso: 'FR', name: 'France', code: '+33', flag: '🇫🇷' },
  { iso: 'GA', name: 'Gabon', code: '+241', flag: '🇬🇦' },
  { iso: 'GM', name: 'Gambia', code: '+220', flag: '🇬🇲' },
  { iso: 'GE', name: 'Georgia', code: '+995', flag: '🇬🇪' },
  { iso: 'DE', name: 'Germany', code: '+49', flag: '🇩🇪' },
  { iso: 'GH', name: 'Ghana', code: '+233', flag: '🇬🇭' },
  { iso: 'GR', name: 'Greece', code: '+30', flag: '🇬🇷' },
  { iso: 'GD', name: 'Grenada', code: '+1473', flag: '🇬🇩' },
  { iso: 'GT', name: 'Guatemala', code: '+502', flag: '🇬🇹' },
  { iso: 'GN', name: 'Guinea', code: '+224', flag: '🇬🇳' },
  { iso: 'GW', name: 'Guinea-Bissau', code: '+245', flag: '🇬🇼' },
  { iso: 'GY', name: 'Guyana', code: '+592', flag: '🇬🇾' },
  { iso: 'HT', name: 'Haiti', code: '+509', flag: '🇭🇹' },
  { iso: 'HN', name: 'Honduras', code: '+504', flag: '🇭🇳' },
  { iso: 'HK', name: 'Hong Kong', code: '+852', flag: '🇭🇰' },
  { iso: 'HU', name: 'Hungary', code: '+36', flag: '🇭🇺' },
  { iso: 'IS', name: 'Iceland', code: '+354', flag: '🇮🇸' },
  { iso: 'IN', name: 'India', code: '+91', flag: '🇮🇳' },
  { iso: 'ID', name: 'Indonesia', code: '+62', flag: '🇮🇩' },
  { iso: 'IR', name: 'Iran', code: '+98', flag: '🇮🇷' },
  { iso: 'IQ', name: 'Iraq', code: '+964', flag: '🇮🇶' },
  { iso: 'IE', name: 'Ireland', code: '+353', flag: '🇮🇪' },
  { iso: 'IT', name: 'Italy', code: '+39', flag: '🇮🇹' },
  { iso: 'CI', name: 'Ivory Coast', code: '+225', flag: '🇨🇮' },
  { iso: 'JM', name: 'Jamaica', code: '+1876', flag: '🇯🇲' },
  { iso: 'JP', name: 'Japan', code: '+81', flag: '🇯🇵' },
  { iso: 'JO', name: 'Jordan', code: '+962', flag: '🇯🇴' },
  { iso: 'KZ', name: 'Kazakhstan', code: '+7', flag: '🇰🇿' },
  { iso: 'KE', name: 'Kenya', code: '+254', flag: '🇰🇪' },
  { iso: 'KW', name: 'Kuwait', code: '+965', flag: '🇰🇼' },
  { iso: 'KG', name: 'Kyrgyzstan', code: '+996', flag: '🇰🇬' },
  { iso: 'LA', name: 'Laos', code: '+856', flag: '🇱🇦' },
  { iso: 'LV', name: 'Latvia', code: '+371', flag: '🇱🇻' },
  { iso: 'LB', name: 'Lebanon', code: '+961', flag: '🇱🇧' },
  { iso: 'LS', name: 'Lesotho', code: '+266', flag: '🇱🇸' },
  { iso: 'LR', name: 'Liberia', code: '+231', flag: '🇱🇷' },
  { iso: 'LY', name: 'Libya', code: '+218', flag: '🇱🇾' },
  { iso: 'LI', name: 'Liechtenstein', code: '+423', flag: '🇱🇮' },
  { iso: 'LT', name: 'Lithuania', code: '+370', flag: '🇱🇹' },
  { iso: 'LU', name: 'Luxembourg', code: '+352', flag: '🇱🇺' },
  { iso: 'MO', name: 'Macau', code: '+853', flag: '🇲🇴' },
  { iso: 'MG', name: 'Madagascar', code: '+261', flag: '🇲🇬' },
  { iso: 'MW', name: 'Malawi', code: '+265', flag: '🇲🇼' },
  { iso: 'MY', name: 'Malaysia', code: '+60', flag: '🇲🇾' },
  { iso: 'MV', name: 'Maldives', code: '+960', flag: '🇲🇻' },
  { iso: 'ML', name: 'Mali', code: '+223', flag: '🇲🇱' },
  { iso: 'MT', name: 'Malta', code: '+356', flag: '🇲🇹' },
  { iso: 'MR', name: 'Mauritania', code: '+222', flag: '🇲🇷' },
  { iso: 'MU', name: 'Mauritius', code: '+230', flag: '🇲🇺' },
  { iso: 'MX', name: 'Mexico', code: '+52', flag: '🇲🇽' },
  { iso: 'MD', name: 'Moldova', code: '+373', flag: '🇲🇩' },
  { iso: 'MC', name: 'Monaco', code: '+377', flag: '🇲🇨' },
  { iso: 'MN', name: 'Mongolia', code: '+976', flag: '🇲🇳' },
  { iso: 'ME', name: 'Montenegro', code: '+382', flag: '🇲🇪' },
  { iso: 'MA', name: 'Morocco', code: '+212', flag: '🇲🇦' },
  { iso: 'MZ', name: 'Mozambique', code: '+258', flag: '🇲🇿' },
  { iso: 'MM', name: 'Myanmar', code: '+95', flag: '🇲🇲' },
  { iso: 'NA', name: 'Namibia', code: '+264', flag: '🇳🇦' },
  { iso: 'NP', name: 'Nepal', code: '+977', flag: '🇳🇵' },
  { iso: 'NL', name: 'Netherlands', code: '+31', flag: '🇳🇱' },
  { iso: 'NZ', name: 'New Zealand', code: '+64', flag: '🇳🇿' },
  { iso: 'NI', name: 'Nicaragua', code: '+505', flag: '🇳🇮' },
  { iso: 'NE', name: 'Niger', code: '+227', flag: '🇳🇪' },
  { iso: 'NG', name: 'Nigeria', code: '+234', flag: '🇳🇬' },
  { iso: 'KP', name: 'North Korea', code: '+850', flag: '🇰🇵' },
  { iso: 'MK', name: 'North Macedonia', code: '+389', flag: '🇲🇰' },
  { iso: 'NO', name: 'Norway', code: '+47', flag: '🇳🇴' },
  { iso: 'OM', name: 'Oman', code: '+968', flag: '🇴🇲' },
  { iso: 'PK', name: 'Pakistan', code: '+92', flag: '🇵🇰' },
  { iso: 'PS', name: 'Palestine', code: '+970', flag: '🇵🇸' },
  { iso: 'PA', name: 'Panama', code: '+507', flag: '🇵🇦' },
  { iso: 'PG', name: 'Papua New Guinea', code: '+675', flag: '🇵🇬' },
  { iso: 'PY', name: 'Paraguay', code: '+595', flag: '🇵🇾' },
  { iso: 'PE', name: 'Peru', code: '+51', flag: '🇵🇪' },
  { iso: 'PH', name: 'Philippines', code: '+63', flag: '🇵🇭' },
  { iso: 'PL', name: 'Poland', code: '+48', flag: '🇵🇱' },
  { iso: 'PT', name: 'Portugal', code: '+351', flag: '🇵🇹' },
  { iso: 'PR', name: 'Puerto Rico', code: '+1787', flag: '🇵🇷' },
  { iso: 'QA', name: 'Qatar', code: '+974', flag: '🇶🇦' },
  { iso: 'RO', name: 'Romania', code: '+40', flag: '🇷🇴' },
  { iso: 'RU', name: 'Russia', code: '+7', flag: '🇷🇺' },
  { iso: 'RW', name: 'Rwanda', code: '+250', flag: '🇷🇼' },
  { iso: 'SA', name: 'Saudi Arabia', code: '+966', flag: '🇸🇦' },
  { iso: 'SN', name: 'Senegal', code: '+221', flag: '🇸🇳' },
  { iso: 'RS', name: 'Serbia', code: '+381', flag: '🇷🇸' },
  { iso: 'SC', name: 'Seychelles', code: '+248', flag: '🇸🇨' },
  { iso: 'SL', name: 'Sierra Leone', code: '+232', flag: '🇸🇱' },
  { iso: 'SG', name: 'Singapore', code: '+65', flag: '🇸🇬' },
  { iso: 'SK', name: 'Slovakia', code: '+421', flag: '🇸🇰' },
  { iso: 'SI', name: 'Slovenia', code: '+386', flag: '🇸🇮' },
  { iso: 'SB', name: 'Solomon Islands', code: '+677', flag: '🇸🇧' },
  { iso: 'SO', name: 'Somalia', code: '+252', flag: '🇸🇴' },
  { iso: 'ZA', name: 'South Africa', code: '+27', flag: '🇿🇦' },
  { iso: 'KR', name: 'South Korea', code: '+82', flag: '🇰🇷' },
  { iso: 'SS', name: 'South Sudan', code: '+211', flag: '🇸🇸' },
  { iso: 'ES', name: 'Spain', code: '+34', flag: '🇪🇸' },
  { iso: 'LK', name: 'Sri Lanka', code: '+94', flag: '🇱🇰' },
  { iso: 'SD', name: 'Sudan', code: '+249', flag: '🇸🇩' },
  { iso: 'SR', name: 'Suriname', code: '+597', flag: '🇸🇷' },
  { iso: 'SE', name: 'Sweden', code: '+46', flag: '🇸🇪' },
  { iso: 'CH', name: 'Switzerland', code: '+41', flag: '🇨🇭' },
  { iso: 'SY', name: 'Syria', code: '+963', flag: '🇸🇾' },
  { iso: 'TW', name: 'Taiwan', code: '+886', flag: '🇹🇼' },
  { iso: 'TJ', name: 'Tajikistan', code: '+992', flag: '🇹🇯' },
  { iso: 'TZ', name: 'Tanzania', code: '+255', flag: '🇹🇿' },
  { iso: 'TH', name: 'Thailand', code: '+66', flag: '🇹🇭' },
  { iso: 'TL', name: 'Timor-Leste', code: '+670', flag: '🇹🇱' },
  { iso: 'TG', name: 'Togo', code: '+228', flag: '🇹🇬' },
  { iso: 'TO', name: 'Tonga', code: '+676', flag: '🇹🇴' },
  { iso: 'TT', name: 'Trinidad and Tobago', code: '+1868', flag: '🇹🇹' },
  { iso: 'TN', name: 'Tunisia', code: '+216', flag: '🇹🇳' },
  { iso: 'TR', name: 'Turkey', code: '+90', flag: '🇹🇷' },
  { iso: 'TM', name: 'Turkmenistan', code: '+993', flag: '🇹🇲' },
  { iso: 'UG', name: 'Uganda', code: '+256', flag: '🇺🇬' },
  { iso: 'UA', name: 'Ukraine', code: '+380', flag: '🇺🇦' },
  { iso: 'AE', name: 'United Arab Emirates', code: '+971', flag: '🇦🇪' },
  { iso: 'GB', name: 'United Kingdom', code: '+44', flag: '🇬🇧' },
  { iso: 'UY', name: 'Uruguay', code: '+598', flag: '🇺🇾' },
  { iso: 'UZ', name: 'Uzbekistan', code: '+998', flag: '🇺🇿' },
  { iso: 'VU', name: 'Vanuatu', code: '+678', flag: '🇻🇺' },
  { iso: 'VA', name: 'Vatican City', code: '+379', flag: '🇻🇦' },
  { iso: 'VE', name: 'Venezuela', code: '+58', flag: '🇻🇪' },
  { iso: 'VN', name: 'Vietnam', code: '+84', flag: '🇻🇳' },
  { iso: 'YE', name: 'Yemen', code: '+967', flag: '🇾🇪' },
  { iso: 'ZM', name: 'Zambia', code: '+260', flag: '🇿🇲' },
  { iso: 'ZW', name: 'Zimbabwe', code: '+263', flag: '🇿🇼' },
]

export function findPhoneCode(code: string | null | undefined): PhoneCode | undefined {
  if (!code) return undefined
  return PHONE_CODES.find(p => p.code === code)
}
